### ISSUE TITLE
Translation works good except calendar month name

### ISSUE THREAD

**Issue by nimeshk-itpath** [SeppPenner/Telerik.Ui.for.Blazor.German.Resources#1]
I'm using latest resource file (2.17.0) but it looks like german keyword is missing for month name, please follow screenshot here:

https://www.screencast.com/t/uA5zfKmrRn

here is working example from telerik team, but I'm not sure which key should be there in resource for translation of month name.

https://demos.telerik.com/blazor-ui/datetimepicker/globalization?_ga=2.159488125.1375805730.1603083665-1247909985.1567661378

Weekday names still Mon, Tue , Wed ... needs to be converted into german.

**Comment by SeppPenner** [comment]
Hi, thanks for the finding. But as far as I know, this is something Telerik needs to fix... The month name is generated from https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#MMMM_Specifier for the current culture. I will ask the Telerik support and see if they can help.

Just one more question: Do you use client side or server side Blazor?

**Comment by SeppPenner** [comment]
By the way, in my customer project (Sorry, I can't show you more), it seems to work properly: 
![grafik](https://user-images.githubusercontent.com/9639361/96629244-a5173500-1313-11eb-8ded-76b393f2b7b0.png)

I'm running a server side project. Maybe this is an issue with client side Blazor?

**Comment by nimeshk-itpath** [comment]
I'm using server side blazor but it seems issue is with only calendar control, everything else looks good 👍

**Comment by nimeshk-itpath** [comment]
I'm thinking keywords are missing in resource file for weekday and calendar name.

**Comment by SeppPenner** [comment]
So, these are the strings from Telerik.dll (Reverse engineered): 
[StringsWithKeyValue.txt](https://github.com/SeppPenner/Telerik.Ui.for.Blazor.German.Resources/files/5424996/StringsWithKeyValue.txt)

These are the keys only (in English):
[Strings.txt](https://github.com/SeppPenner/Telerik.Ui.for.Blazor.German.Resources/files/5425004/Strings.txt)

There are my keys set for the German resources: 
[Strings_German.txt](https://github.com/SeppPenner/Telerik.Ui.for.Blazor.German.Resources/files/5425018/Strings_German.txt)

And this is the comparison view of the strings (Keys) with KDiff3 to see if keys are missing:
![Comparison](https://user-images.githubusercontent.com/9639361/96916125-6ca86000-14a7-11eb-8f87-1f3f35fb5428.PNG)

As you can see on the right side, there is no difference between the keys in the German and English (from Telerik) resource files. There is no key for the month names as the month names are set with a string identifier like https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#MMMM_Specifier I would say...

Just some more questions:
* Did you use `services.AddSingleton(typeof(ITelerikStringLocalizer), typeof(CustomTelerikStringLocalizer));` in your `ConfigureServices` method in the `Startup` class?
* How do you setup your localization? E.g. my code looks like this (`Configure` method in `Startup` class):

```csharp
// Add localization
app.UseRequestLocalization(options =>
{
    options.AddSupportedCultures("en-US", "de-DE");
    options.AddSupportedUICultures("en-US", "de-DE");

    // Cookie culture provider is included by default, but we want it to be the only one.
    options.RequestCultureProviders.Clear();
    options.RequestCultureProviders.Add(new CookieRequestCultureProvider());

    // Set the default locale to the one set by the configuration.
    options.SetDefaultCulture("de-DE");
});
```

If that doesn't help, I guess, you should ask Telerik for help... I can't do anything with this issue, I guess :confused:

Or you wait until I'm done with version 2.18.0 of the Telerik library (It's out till yesterday: https://www.telerik.com/support/whats-new/blazor-ui/release-history) and see if this already fixes your issue. I will probably add the resources file tomorrow.

**Comment by nimeshk-itpath** [comment]
Just upgraded telerik version to 2.18.0 and added below code as you mentioned:

      // Add localization
      app.UseRequestLocalization(options =>
      {
        options.AddSupportedCultures("en-US", "de-DE");
        options.AddSupportedUICultures("en-US", "de-DE");

        // Cookie culture provider is included by default, but we want it to be the only one.
        options.RequestCultureProviders.Clear();
        options.RequestCultureProviders.Add(new CookieRequestCultureProvider());

        // Set the default locale to the one set by the configuration.
        options.SetDefaultCulture("de-DE");
      });

**Interesting my issue is fixed now and month/weekday names are showing in German language now.**

I think below two lines did trick for me, but I'm not sure why only calendar wasn't works:

    // Cookie culture provider is included by default, but we want it to be the only one.
    options.RequestCultureProviders.Clear();
    options.RequestCultureProviders.Add(new CookieRequestCultureProvider());
   
Anyways thanks for the help!!!

**Comment by SeppPenner** [comment]
@nimeshk-itpath Good to know :) This is something, I did find on a page where the localization feature was explained (Don't know anymore where I got this from to be honest).

I guess, the problem was that the `RequestCultureProviders` contain a default culture (English) and therefore use English as fallback / first option if you don't clear them.
